{{- if .Values.favicon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duna.fullname" . }}-favicon
data:
  favicon.ico: |-
    {{ .Files.Get .Values.favicon.filePath | b64enc | quote }}
{{- end }}
